version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306